In [4]:
#1.Create a numpy array starting from 2 till 50 with a stepsize of 3.

import numpy as np
a = np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [19]:
#2.Accept two lists of 5 elements each from the user.Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

import numpy as np
# creating an empty list 
lst = [] 
lst1 = [] 
  
print("Enter 5 values for List1") 
# iterating till the range 
for i in range(0, 5): 
    ele = int(input()) 
  
    lst.append(ele) # adding the element 
      
print("The List1 is :",lst) 


print("Enter 5 values for List2") 
# iterating till the range 
for i in range(0, 5): 
    ele1 = int(input()) 
  
    lst1.append(ele1) # adding the element 
      
print("The List2 is :",lst1) 

a = np.array(lst)
print("numpy array1",a)

b = np.array(lst1)
print("numpy array2",b)

z=np.concatenate((a,b))  
print("concatenated array z is ",z)
print("sorted array",np.sort(z))


Enter 5 values for List1
2
1
3
5
4
The List1 is : [2, 1, 3, 5, 4]
Enter 5 values for List2
9
6
8
10
7
The List2 is : [9, 6, 8, 10, 7]
numpy array1 [2 1 3 5 4]
numpy array2 [ 9  6  8 10  7]
concatenated array z is  [ 2  1  3  5  4  9  6  8 10  7]
sorted array [ 1  2  3  4  5  6  7  8  9 10]


In [37]:
#3.Write a code snippet to find the dimensions of a ndarray and its size.
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
#print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
#print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
#print("Array stores elements of type: ", arr.dtype)


Shape of array:  (2, 3)
Size of array:  6


In [34]:
#4.How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims

import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print("1D array  :",a)
print("1D array shape :",a.shape)

a1 = a[np.newaxis, :]
print("2D array  :",a1)
print("After converting a 1D array into a 2D array the shape :",a1.shape)

1D array  : [1 2 3 4 5 6]
1D array shape : (6,)
2D array  : [[1 2 3 4 5 6]]
After converting a 1D array into a 2D array the shape : (1, 6)


In [35]:
#5.Consider two square numpy arrays. Stack them vertically and horizontally.Hint: Use vstack(), hstack()


import numpy as np

array_2d = np.array([1, 2, 3])

print("Source Array1:\n",array_2d)

array_2d_square = np.square(array_2d)

print("Squared Array1:\n",array_2d_square)


array_2d1 = np.array([4, 5, 6])

print("Source Array1:\n",array_2d1)

array_2d_square1 = np.square(array_2d1)

print("Squared Array1:\n",array_2d_square1)



print('Horizontal Append:', np.hstack((array_2d_square, array_2d_square1)))

print('Vertical Append:', np.vstack((array_2d_square, array_2d_square1)))

Source Array1:
 [1 2 3]
Squared Array1:
 [1 4 9]
Source Array1:
 [4 5 6]
Squared Array1:
 [16 25 36]
Horizontal Append: [ 1  4  9 16 25 36]
Vertical Append: [[ 1  4  9]
 [16 25 36]]


In [31]:
# 6.How to get unique items and counts of unique items?

import numpy as np
a=np.unique([0,1,2,0,2,3,4,3,0,4])
print("unique items :",a)
print("counts of unique items :",len(a))


unique items : [0 1 2 3 4]
counts of unique items : 5
